version: '3'

tasks:
  default:
    cmds:
    - task --list

  run-dev:
    desc: Start dev server with hot reload
    dir: src
    cmds:
    - air

  build:
    desc: Build and push Docker image
    vars:
      COMMIT_SHA:
        sh: git rev-parse --short HEAD
    cmds:
    - docker buildx build --platform linux/amd64 -t fizzbuzz2/oci-storage:{{.COMMIT_SHA}} --push .
    - 'sed -i "" "s/tag: .*/tag: \"{{.COMMIT_SHA}}\"/" helm/values.yaml'
    - echo "Pushed fizzbuzz2/oci-storage:{{.COMMIT_SHA}} and updated helm/values.yaml"

  start:
    desc: Start Docker container
    cmds:
    - docker compose up -d

  stop:
    desc: Stop Docker container
    cmds:
    - docker compose down

  helm-template:
    desc: Template the helmchart
    dir: helm
    cmds:
    - helm template . --debug -f values/home/values.yaml > rendered.yaml

  test-unit:
    desc: Run Go unit tests
    dir: src
    cmds:
    - go test ./pkg/... -v

  test-e2e:
    desc: Run full E2E tests (OCI protocol, HTTP API, proxy, auth, backup)
    dir: tests
    cmds:
    - ./test-e2e.sh

  create-auth-secret:
    desc: Create Kubernetes auth secret
    cmds:
    - kubectl create secret generic oci-storage-auth --from-literal=HELM_USERS="admin:secret123,dev:devpass,readonly:readpass" --namespace=kube-infra --dry-run=client -o yaml | kubectl apply -f -

  create-backup-secret:
    desc: Create Kubernetes backup secret (AWS)
    cmds:
    - kubectl create secret generic oci-storage-backup --from-literal=BACKUP_ENABLED="true" --from-literal=BACKUP_PROVIDER="aws" --from-literal=AWS_BUCKET="oci-storage-backup" --from-literal=AWS_REGION="eu-west-1" --from-literal=AWS_ACCESS_KEY_ID="YOUR_ACCESS_KEY" --from-literal=AWS_SECRET_ACCESS_KEY="YOUR_SECRET_KEY" --namespace=kube-infra --dry-run=client -o yaml | kubectl apply -f -

  publish:
    desc: Build, tag, push image and update helm chart (bumps patch version from latest git tag)
    vars:
      LATEST_TAG:
        sh: git tag --sort=-v:refname | head -1 | sed 's/^v//'
      MAJOR:
        sh: git tag --sort=-v:refname | head -1 | sed 's/^v//' | cut -d. -f1
      MINOR:
        sh: git tag --sort=-v:refname | head -1 | sed 's/^v//' | cut -d. -f2
      PATCH:
        sh: git tag --sort=-v:refname | head -1 | sed 's/^v//' | cut -d. -f3
      NEW_PATCH:
        sh: echo $(($(git tag --sort=-v:refname | head -1 | sed 's/^v//' | cut -d. -f3) + 1))
      NEW_VERSION:
        sh: echo "$(git tag --sort=-v:refname | head -1 | sed 's/^v//' | cut -d. -f1).$(git tag --sort=-v:refname | head -1 | sed 's/^v//' | cut -d. -f2).$(($(git tag --sort=-v:refname | head -1 | sed 's/^v//' | cut -d. -f3) + 1))"
      COMMIT_SHA:
        sh: git rev-parse --short HEAD
    cmds:
      - echo "Current version {{.LATEST_TAG}} → New version {{.NEW_VERSION}}"
      - docker buildx build --platform linux/amd64
          --build-arg VERSION={{.NEW_VERSION}}
          --build-arg COMMIT={{.COMMIT_SHA}}
          --build-arg BUILD_TIME={{now | date "2006-01-02T15:04:05Z"}}
          -t fizzbuzz2/oci-storage:v{{.NEW_VERSION}}
          --push .
      - 'sed -i "" "s/^version: .*/version: {{.NEW_VERSION}}/" helm/Chart.yaml'
      - 'sed -i "" "s/^appVersion: .*/appVersion: \"{{.NEW_VERSION}}\"/" helm/Chart.yaml'
      - 'sed -i "" "s/tag: .*/tag: \"v{{.NEW_VERSION}}\"/" helm/values.yaml'
      - git add helm/Chart.yaml helm/values.yaml
      - git commit -m "chore{{":"}} release v{{.NEW_VERSION}}"
      - git tag v{{.NEW_VERSION}}
      - git push origin main --force --no-verify
      - git push origin v{{.NEW_VERSION}} --no-verify
      - echo "Published v{{.NEW_VERSION}} ✓"
