apiVersion: v1
kind: Secret
metadata:
  name: oci-storage-registry
  namespace: oci-storage-test
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "oci-storage.dc-tech.work": {
          "username": "admin",
          "password": "admin",
          "auth": "YWRtaW46YWRtaW4="
        }
      }
    }
