apiVersion: v1
kind: Secret
metadata:
  name: helm-portal-repo
  namespace: kube-infra
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: helm-portal
  url: helm-portal.dc-tech.work
  enableOCI: "true"
  username: admin
  password: admin
